# Site settings
name: 'CS Cheerleader'
description: "Ria Galanos' musings during her first year as a software engineer."
meta_description: 'A blog about the first year of a software engineer.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: 
disqus: 'cscheerleader-com'
mailchimp_url: 
#'//gmail.us3.list-manage.com/subscribe/post?u=522e242c58a077f18018b81be&amp;id=31996b5f19'
cover_image: 'bc_1.jpg'

# Add your GA Tracking Id
ga_analytics: 

# Author
author:
  name: 'Ria Galanos'
  image: 'authorimage.jpg'
  greetings: "Hello, world.  I'm Ria Galanos."
  description: |
    <strong>Software engineer. Computer science education consultant.  Android hobbyist.</strong><br>
    This is a glimpse into my first year as a software engineer.  I hope to take some of the mystery out of what it's like to work at a fast-paced tech company.
  bio: "Software engineer. Computer science education consultant.  Android hobbyist."

# Contact form setings
email: 'ria.galanos@gmail.com'
contact_page_description: "Looking forward to reading what you have to say!"
thankyou_page_description: "Your message has been successfully sent. I will reply soon."

# Social links
twitter: 'cscheerleader'
#facebook: 'username'
github: 'riagalanos'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
#instagram: 'username'
#pinterest: 'username'
linkedin: 'riagalanos'
#producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about
  - text: CV
    url: /cv
  - text: APCS A 
    url: /apcs-a
  - text: Contact Me
    url: /contact  

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
